/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LifeRouteImport } from './routes/life'
import { Route as LandlordInsuranceRouteImport } from './routes/landlord-insurance'
import { Route as HomeInsuranceRouteImport } from './routes/home-insurance'
import { Route as DuplexInsuranceRouteImport } from './routes/duplex-insurance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordInsuranceRoute = LandlordInsuranceRouteImport.update({
  id: '/landlord-insurance',
  path: '/landlord-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeInsuranceRoute = HomeInsuranceRouteImport.update({
  id: '/home-insurance',
  path: '/home-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplexInsuranceRoute = DuplexInsuranceRouteImport.update({
  id: '/duplex-insurance',
  path: '/duplex-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auto': typeof AutoRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/duplex-insurance': typeof DuplexInsuranceRoute
  '/home-insurance': typeof HomeInsuranceRoute
  '/landlord-insurance': typeof LandlordInsuranceRoute
  '/life': typeof LifeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auto': typeof AutoRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/duplex-insurance': typeof DuplexInsuranceRoute
  '/home-insurance': typeof HomeInsuranceRoute
  '/landlord-insurance': typeof LandlordInsuranceRoute
  '/life': typeof LifeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auto': typeof AutoRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/duplex-insurance': typeof DuplexInsuranceRoute
  '/home-insurance': typeof HomeInsuranceRoute
  '/landlord-insurance': typeof LandlordInsuranceRoute
  '/life': typeof LifeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin_/dashboard': typeof AdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/auto'
    | '/business'
    | '/contact'
    | '/duplex-insurance'
    | '/home-insurance'
    | '/landlord-insurance'
    | '/life'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/auto'
    | '/business'
    | '/contact'
    | '/duplex-insurance'
    | '/home-insurance'
    | '/landlord-insurance'
    | '/life'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/auto'
    | '/business'
    | '/contact'
    | '/duplex-insurance'
    | '/home-insurance'
    | '/landlord-insurance'
    | '/life'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin_/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AutoRoute: typeof AutoRoute
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  DuplexInsuranceRoute: typeof DuplexInsuranceRoute
  HomeInsuranceRoute: typeof HomeInsuranceRoute
  LandlordInsuranceRoute: typeof LandlordInsuranceRoute
  LifeRoute: typeof LifeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord-insurance': {
      id: '/landlord-insurance'
      path: '/landlord-insurance'
      fullPath: '/landlord-insurance'
      preLoaderRoute: typeof LandlordInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-insurance': {
      id: '/home-insurance'
      path: '/home-insurance'
      fullPath: '/home-insurance'
      preLoaderRoute: typeof HomeInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplex-insurance': {
      id: '/duplex-insurance'
      path: '/duplex-insurance'
      fullPath: '/duplex-insurance'
      preLoaderRoute: typeof DuplexInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AutoRoute: AutoRoute,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  DuplexInsuranceRoute: DuplexInsuranceRoute,
  HomeInsuranceRoute: HomeInsuranceRoute,
  LandlordInsuranceRoute: LandlordInsuranceRoute,
  LifeRoute: LifeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
